import path from "node:path";
import { lstat, readdir, unlink } from "node:fs/promises";
import { getCustomOrderConfig, prepareCustomOrderUploadDirectory, STORED_MODEL_FILENAME } from "../config/customOrders.js";

// All upload middleware instances and the cleanup worker share this coordinator.
// Run one API process per directory; a cluster needs a shared quota coordinator.
const directories = new Map();

function stateFor(directory) {
  let state = directories.get(directory);
  if (!state) {
    state = { pending: Promise.resolve(), active: new Map() };
    directories.set(directory, state);
  }
  return state;
}

function exclusive(state, action) {
  const result = state.pending.then(action);
  state.pending = result.catch(() => {});
  return result;
}

export function storageFullError() {
  return Object.assign(new Error("A modellfájlok tárhelye megtelt. Kérjük, próbálja újra később, vagy küldje el a kérést fájl nélkül, leírással."), {
    status: 503, code: "CUSTOM_ORDER_STORAGE_FULL",
  });
}

// Never recurse or follow links. Unknown regular files count toward the quota,
// but only names generated by this application are eligible for deletion.
async function scan(directory, state, config, now, removeExpired) {
  // Releases may run while filesystem reads await. Use the same snapshot for
  // the reserved totals and disk exclusions so completed uploads count once.
  const active = new Map(state.active);
  let usedBytes = [...active.values()].reduce((sum, size) => sum + size, 0);
  let fileCount = active.size;
  let removed = 0;
  for (const name of await readdir(directory)) {
    if (active.has(name)) continue;
    const filename = path.join(directory, name);
    let info;
    try { info = await lstat(filename); }
    catch (error) {
      if (error.code === "ENOENT") continue;
      throw error;
    }
    // Upload storage is deliberately flat. Unexpected directories/links cannot
    // be safely accounted for, so refuse new writes until an operator fixes it.
    if (!info.isFile() || info.isSymbolicLink()) {
      if (!removeExpired) throw storageFullError();
      continue;
    }
    if (removeExpired && STORED_MODEL_FILENAME.test(name) && now - info.mtimeMs >= config.retentionMs) {
      try {
        await unlink(filename);
        removed++;
        continue;
      } catch (error) {
        if (error.code === "ENOENT") continue;
        // Continue deleting other expired files, but keep failures charged.
        console.error("Custom order expired file cleanup failed.");
      }
    }
    usedBytes += info.size;
    fileCount++;
  }
  return { usedBytes, fileCount, removed };
}

export async function reserveCustomOrderFile(config, filename) {
  if (!STORED_MODEL_FILENAME.test(filename)) throw new Error("Invalid stored model filename.");
  const directory = await prepareCustomOrderUploadDirectory(config.uploadDir);
  const state = stateFor(directory);
  return exclusive(state, async () => {
    if (state.active.has(filename)) throw new Error("Model filename already reserved.");
    const { usedBytes, fileCount } = await scan(directory, state, config, Date.now(), false);
    // Reserve the whole per-file allowance before opening the destination.
    // Reading Content-Length or charging only completed files races with uploads.
    if (usedBytes + config.maxFileSizeBytes > config.maxStorageBytes || fileCount >= config.maxFiles) throw storageFullError();
    state.active.set(filename, config.maxFileSizeBytes);
    let released = false;
    return {
      directory,
      release() {
        if (!released) {
          released = true;
          state.active.delete(filename);
        }
      },
    };
  });
}

export async function cleanupCustomOrderFiles(config = getCustomOrderConfig(), now = Date.now()) {
  const directory = await prepareCustomOrderUploadDirectory(config.uploadDir);
  const state = stateFor(directory);
  return exclusive(state, () => scan(directory, state, config, now, true));
}

export async function startCustomOrderCleanup(config = getCustomOrderConfig()) {
  // Reconcile files left by previous processes before accepting any requests.
  await cleanupCustomOrderFiles(config);
  let running = false;
  const timer = setInterval(async () => {
    if (running) return;
    running = true;
    try { await cleanupCustomOrderFiles(config); }
    catch { console.error("Custom order storage cleanup failed."); }
    finally { running = false; }
  }, config.cleanupIntervalMs);
  timer.unref();
  return () => clearInterval(timer);
}
